window._CCSettings = {
    platform: "web-mobile",
    groupList: [
        "default"
    ],
    collisionMatrix: [
        [
            true
        ]
    ],
    rawAssets: {
        assets: {
            "74af2yZMFG+ZTYupfwliT0": [
                "BGM/Bg.mp3",
                "cc.AudioClip"
            ],
            "8fSZ/U6ohAKIc3t9ev8w4z": [
                "Buff/Buff.prefab",
                "cc.Prefab"
            ],
            "c45e/ddRZDsJ4zJ6k/bFPk": [
                "JSON/Network.json",
                "cc.JsonAsset"
            ],
            "06bVn1APpKv7FMEK5Id3kQ": [
                "Prefabs/Coins.prefab",
                "cc.Prefab"
            ],
            "91U+XQfHRDlparf7w8MfsN": [
                "Prefabs/FloorGRP.prefab",
                "cc.Prefab"
            ],
            a6YyX0jCVHj4XXF4XTPOyV: [
                "Prefabs/Goal.prefab",
                "cc.Prefab"
            ],
            daHlQoZpNKab7WrGW8oPZu: [
                "Prefabs/Hero.prefab",
                "cc.Prefab"
            ],
            "1fzWblw4VLYZCIJNpQxYU+": [
                "Prefabs/Main Camera.prefab",
                "cc.Prefab"
            ],
            "81mJVqOWhP2Yd1PcwdvZhM": [
                "Prefabs/MinusLabel.prefab",
                "cc.Prefab"
            ],
            "382Oa6ZzZAwoPfh2TblXVa": [
                "Prefabs/Obstacle.prefab",
                "cc.Prefab"
            ],
            "6eXmBhpJBLm6PeO2KjWQLr": [
                "Prefabs/Particles/CoinsParticle.prefab",
                "cc.Prefab"
            ],
            "1547sYAFBEvpxItHQVtvXp": [
                "Prefabs/Puddle.prefab",
                "cc.Prefab"
            ],
            "eaIt/HIKNAtr5nMMLj7xsr": [
                "Prefabs/Scafolding.prefab",
                "cc.Prefab"
            ],
            "74gwuO5bNBl4n7KFW0Bs4V": [
                "Prefabs/SportDrinks.prefab",
                "cc.Prefab"
            ],
            "2cSug52bVId5OE+LAasjY6": [
                "Prefabs/VictoryPrefab.prefab",
                "cc.Prefab"
            ],
            "22WVmq81JPiLOBlkiLcByM": [
                "SoundFX/Obstacle/SFX_Explosion.mp3",
                "cc.AudioClip"
            ],
            "8cWpXH9IlKg6e2njFWkoC5": [
                "SoundFX/Obstacle/SFX_Hit1.mp3",
                "cc.AudioClip"
            ],
            "a76Ld3TQlN46BoTJrI7+hh": [
                "SoundFX/Obstacle/SFX_Hit2.mp3",
                "cc.AudioClip"
            ],
            "9a5+NPYH1Di5VzvPjUzHr2": [
                "SoundFX/Obstacle/SFX_Hit3.mp3",
                "cc.AudioClip"
            ],
            f7HleAe95F5Zpxza43Hnhx: [
                "SoundFX/Obstacle/SFX_Hit4.mp3",
                "cc.AudioClip"
            ],
            "16DzTsxxBFsocLxvhRCk1K": [
                "SoundFX/SFX_BicycleRing_StartGame.wav",
                "cc.AudioClip"
            ],
            "42jIP8ZbVO9o3SNRBYY/JA": [
                "SoundFX/SFX_Bicycle_Cycling_Loop_1min.mp3",
                "cc.AudioClip"
            ],
            "5cghFZfKdEoYlMB5RF1Alb": [
                "SoundFX/SFX_Drinking.mp3",
                "cc.AudioClip"
            ],
            a6vF1gEJZEH79aJFnesnWl: [
                "SoundFX/SFX_EpicWin_EndGame.mp3",
                "cc.AudioClip"
            ],
            "28Ni7pqlFLerMXvYlGCotk": [
                "SoundFX/SFX_Jump.mp3",
                "cc.AudioClip"
            ]
        },
        internal: {
            "14TDKXr2NJ6LjvHPops74o": [
                "effects/builtin-2d-gray-sprite.effect",
                "cc.EffectAsset"
            ],
            "0ek66qC1NOQLjgYmi04HvX": [
                "effects/builtin-2d-spine.effect",
                "cc.EffectAsset"
            ],
            "28dPjdQWxEQIG3VVl1Qm6T": [
                "effects/builtin-2d-sprite.effect",
                "cc.EffectAsset"
            ],
            "2afAA24LNP4YmYiaVLiivs": [
                "effects/builtin-3d-trail.effect",
                "cc.EffectAsset"
            ],
            c0BAyVxX9JzZy8EjFrc9DU: [
                "effects/builtin-clear-stencil.effect",
                "cc.EffectAsset"
            ],
            "6dkeWRTOBGXICfYQ7JUBnG": [
                "effects/builtin-unlit.effect",
                "cc.EffectAsset"
            ],
            "6fgBCSDDdPMInvyNlggls2": [
                "materials/builtin-2d-base.mtl",
                "cc.Material"
            ],
            "3ae7efMv1CLq2ilvUY/tQi": [
                "materials/builtin-2d-gray-sprite.mtl",
                "cc.Material"
            ],
            "7a/QZLET9IDreTiBfRn2PD": [
                "materials/builtin-2d-spine.mtl",
                "cc.Material"
            ],
            "ecpdLyjvZBwrvm+cedCcQy": [
                "materials/builtin-2d-sprite.mtl",
                "cc.Material"
            ],
            "46bU+b5fROqIXVPG6aZWWK": [
                "materials/builtin-3d-trail.mtl",
                "cc.Material"
            ],
            cffgu4qBxEqa150o1DmRAy: [
                "materials/builtin-clear-stencil.mtl",
                "cc.Material"
            ],
            "2aKWBXJHxKHLvrBUi2yYZQ": [
                "materials/builtin-unlit.mtl",
                "cc.Material"
            ]
        }
    },
    launchScene: "db://assets/Scenes/Levels/Level1.fire",
    scenes: [
        {
            url: "db://assets/Scenes/Levels/Level1.fire",
            uuid: "f3Z1KNQj9O0aef4dIt/HAV"
        },
        {
            url: "db://assets/Scenes/Levels/Level10.fire",
            uuid: "29jW9wyHxOao5gkUwvdB9K"
        },
        {
            url: "db://assets/Scenes/Levels/Level2.fire",
            uuid: "71SXaL5sxLjIQj7FWxCYst"
        },
        {
            url: "db://assets/Scenes/Levels/Level3.fire",
            uuid: "f2W0Sg8UpPoJLDeivhEWlz"
        },
        {
            url: "db://assets/Scenes/Levels/Level4.fire",
            uuid: "3cg+uqC5VEuJf2i7xVLYeb"
        },
        {
            url: "db://assets/Scenes/Levels/Level5.fire",
            uuid: "a6IaA4XKZFNKhNhiifT8AF"
        },
        {
            url: "db://assets/Scenes/Levels/Level6.fire",
            uuid: "88QcKx7FdGmpuJ5olptNfp"
        },
        {
            url: "db://assets/Scenes/Levels/Level7.fire",
            uuid: "844DoY4oVOeLu1fGsiZQGX"
        },
        {
            url: "db://assets/Scenes/Levels/Level8.fire",
            uuid: "3aGn6oq0pOoYa5DXtWOY7/"
        },
        {
            url: "db://assets/Scenes/Levels/Level9.fire",
            uuid: "6c1/VfNCJGj74VFE88Y6V7"
        },
        {
            url: "db://assets/Scenes/Levels/MainMenu.fire",
            uuid: "d8TzQXI+1Cmbh4ZCk5/ODZ"
        }
    ],
    packedAssets: {
        "010946c80": [
            "1547sYAFBEvpxItHQVtvXp",
            "5b8qDzDw9MmIfoAr+/fHel"
        ],
        "029f6769f": [
            "0ddgS2FmpMya8Laf7lDSnD",
            "0f04RpJNZCSJKPZUx4/O/Q",
            "13VY83XL9Gr7Wzt942LCWY",
            "24DPYVtRRAZbGIxO94dlYz",
            "36MFSPMVFPELQJlRZyhmRc",
            "37PG/rFvNIaokCOYzM/AZ9",
            "3cg+uqC5VEuJf2i7xVLYeb",
            "3dIekwH7VHEp/88ewubbYW",
            "5aJct5pf9KrJLOcvbo6JyH",
            "5b8qDzDw9MmIfoAr+/fHel",
            "6fQMsWZapBEp4GWr1ykQhA",
            "7dMDA8iHdKp47YbphWeqFV",
            "82NH9RLcxH0p+zY7xLqkJy",
            "84wKut40NA+KC8Z/5qHZQJ",
            "aaYWtUd9VKf7X07EYiL2Gl",
            "adr3XijbBIlZ3PeU4I6FKc",
            "aeBkqD1+9NXopwsj3ACUs9",
            "c02XxJQd1KLaccwBPKOkd6",
            "c50CwyRRpJ2p2FNNDW5AAH",
            "c6RFF9oNVIK5yOjpv5SraX",
            "c8+qc2mdJBVLvYQIlHqBih",
            "ccyp4Ts+FMs6kAkyECgIcf",
            "d9R2w8GvhCvpX5ok6iEzzm",
            "e2UeGsGjtJjrLqHERrD/h/",
            "e4krZ2nzdGLIiazWxiK0EK",
            "e4uTTPCidHDquC1IGwjTpL",
            "e452s0o4JJh7EPbzIPLnEM",
            "ee25qaZNRCTI7z84Ts3I8f",
            "f2+3OFeUhNV4Jq2yGqmlIQ",
            "f7S1nL4lxGrKXpkWPRtXdS"
        ],
        "045d0e3da": [
            "03KnKn+b9NlZidQiCaoIB5",
            "10lZZrAFVBjrxi0mWOpfMq",
            "159hpjx/FF5b67s8vn5F/U",
            "297YGK3MxDRKXbSHklrRH0",
            "2cSug52bVId5OE+LAasjY6",
            "42CLLMedBEsLc2GBLhc/4x",
            "52xSDgNuFD3aHGT+t2kut6",
            "8eX6ioyMxBQaZN/8hBOHr0",
            "9fNz6eySdEtbCfSPMY44ty",
            "a6vF1gEJZEH79aJFnesnWl",
            "cbLGoCuelOu76HdBz/JcbA",
            "fcOUkOEX5FxrdM3K3uJw0y"
        ],
        "04eb7c0ee": [
            "0ddgS2FmpMya8Laf7lDSnD",
            "0f04RpJNZCSJKPZUx4/O/Q",
            "17PxwbWS1Ps61J2aTFHnY9",
            "19Fvk/WSZDOb0AGw0cPOyH",
            "24DPYVtRRAZbGIxO94dlYz",
            "2erzjVAidCKJN12SYwczPd",
            "36MFSPMVFPELQJlRZyhmRc",
            "37PG/rFvNIaokCOYzM/AZ9",
            "3dIekwH7VHEp/88ewubbYW",
            "5aJct5pf9KrJLOcvbo6JyH",
            "611ibmP4xMDLhNa25yAh7Y",
            "6fQMsWZapBEp4GWr1ykQhA",
            "7dMDA8iHdKp47YbphWeqFV",
            "84wKut40NA+KC8Z/5qHZQJ",
            "95/amvJORNGYpbmAaqMA3m",
            "aaYWtUd9VKf7X07EYiL2Gl",
            "adr3XijbBIlZ3PeU4I6FKc",
            "aeBkqD1+9NXopwsj3ACUs9",
            "b0LzFMPNZMnbeoih5/NSt/",
            "c02XxJQd1KLaccwBPKOkd6",
            "c50CwyRRpJ2p2FNNDW5AAH",
            "c6RFF9oNVIK5yOjpv5SraX",
            "d5xowZ03dNRqlvH0TXFIs2",
            "e2UeGsGjtJjrLqHERrD/h/",
            "e4krZ2nzdGLIiazWxiK0EK",
            "e4uTTPCidHDquC1IGwjTpL",
            "e452s0o4JJh7EPbzIPLnEM",
            "ee25qaZNRCTI7z84Ts3I8f",
            "f3Z1KNQj9O0aef4dIt/HAV",
            "f7S1nL4lxGrKXpkWPRtXdS"
        ],
        "05e864a20": [
            "19Fvk/WSZDOb0AGw0cPOyH",
            "382Oa6ZzZAwoPfh2TblXVa",
            "8cWpXH9IlKg6e2njFWkoC5",
            "9a5+NPYH1Di5VzvPjUzHr2",
            "a76Ld3TQlN46BoTJrI7+hh",
            "f7HleAe95F5Zpxza43Hnhx"
        ],
        "061bd935c": [
            "08XPgce3hL/YD6Sdd0GAT8",
            "0ddgS2FmpMya8Laf7lDSnD",
            "13VY83XL9Gr7Wzt942LCWY",
            "24DPYVtRRAZbGIxO94dlYz",
            "2erzjVAidCKJN12SYwczPd",
            "3126Eq/wtNeazDu6dhTx/T",
            "36MFSPMVFPELQJlRZyhmRc",
            "3dIekwH7VHEp/88ewubbYW",
            "3euf4XW71LM6h/UM2HgGSW",
            "41Pwmd+1JLLLI1/LsDwogk",
            "5aJct5pf9KrJLOcvbo6JyH",
            "5fxfol3JBOP4ETCQc/Lx+9",
            "6fQMsWZapBEp4GWr1ykQhA",
            "82NH9RLcxH0p+zY7xLqkJy",
            "84wKut40NA+KC8Z/5qHZQJ",
            "88QcKx7FdGmpuJ5olptNfp",
            "9d+uXIr5VN7KXiY6H3VR/Y",
            "adr3XijbBIlZ3PeU4I6FKc",
            "aeBkqD1+9NXopwsj3ACUs9",
            "bbK102zWpLmZ/GhJXc/nTE",
            "c6RFF9oNVIK5yOjpv5SraX",
            "e4krZ2nzdGLIiazWxiK0EK",
            "e4mox6w4hF5IJdFlki+I5j",
            "e4uTTPCidHDquC1IGwjTpL",
            "e6K5fUo/hESqkCdmgs255J",
            "f7S1nL4lxGrKXpkWPRtXdS",
            "f7WfLB05tIlaQbh1tEmZpF"
        ],
        "068421011": [
            "16DzTsxxBFsocLxvhRCk1K",
            "1fzWblw4VLYZCIJNpQxYU+",
            "36MFSPMVFPELQJlRZyhmRc",
            "63pbjiMlNGMZj0bUyM7AGe",
            "97gaTOiiVHb7YTgzzER42S",
            "adr3XijbBIlZ3PeU4I6FKc",
            "c6RFF9oNVIK5yOjpv5SraX"
        ],
        "06d3b8b84": [
            "74gwuO5bNBl4n7KFW0Bs4V",
            "82NH9RLcxH0p+zY7xLqkJy"
        ],
        "06e4ae178": [
            "02pUSYSbNOHI2OY08qdPFI",
            "06eGmbtWZBz5UVfJoR6QKf",
            "08bAL9ZUFHT4o+/20I4VdF",
            "0cXmWP/ZdAAaW5ybf/1Kn1",
            "10IY8igtBP+JPKn6bffcRM",
            "17uuvAV31DMq+HCPqEbBHf",
            "1fBzcdlJZKv44jcB6Rme5G",
            "22WAiplX5CfI7IhPOY+Fv8",
            "29zxlrcbVKY6m5paggtwJ2",
            "2bUQMluHJIpryMB4jK6Pya",
            "32ll5Dzh1Oy6RrT9t3kY0i",
            "34MvbmTF9IB5VubONBEaCb",
            "36ZQChEO5Ge4ak+gljDnwl",
            "38Rg6j9GVNPa9foaHuv3Bw",
            "389ug8LLVA5rlizsaSkhIM",
            "39R7kpGqZMaJ9WFBSHnqCj",
            "3bBaPKIDxFs4J4zkokDSUK",
            "3f0T+TpCtG+Iorgfj3MxRA",
            "410KuWtiZJcY6W0Ll6oZt+",
            "52D5cDu5BJkKhGwywmx+8V",
            "53GrEZQDZMNJUJ1nUWdkvo",
            "54BS3AdvxLI4IQtFc2ttKG",
            "56BevKQCdMipfWWsoM0C3P",
            "70tY+pgUhPnJwhVokk0q+g",
            "75yzd36ZNNuJYhQLCuofr9",
            "8730ptfoxHu6rFi0K3jgoL",
            "8enHonnmFDGJeO+j032Mut",
            "93QO3rr2NKGoy4AWGFKrl6",
            "96dVcjibdMYIZOIlNkzHVy",
            "99TXj8fJ9Bnoex5gFdTLM2",
            "a0JuQtvshOp6QUd+b+l0qx",
            "a4wsfNvlFLgbeWohjQf+1c",
            "a9V1DAyBxAPIuOdd/Tn7G5",
            "acAtqBzqZKcrDBCxHwM2Sz",
            "b0WqX0CO5JQLWEYCmpUPi5",
            "b3pi7+qhVG3pxoGSokpELs",
            "b5aW8+N0FG0Y8J6sWehMh6",
            "b82Mgso3lI650goV+OI6WQ",
            "bfD0gE34xHKa/b/HzDrSo6",
            "c00EjsO2ZIELsW8kGvB5zI",
            "cdmzMH5kdAZKMZSqp1vMKO",
            "cfCjM1VM1F5q2eqRPkRrwt",
            "d2hCAAw1hNOryG/YkwzBMR",
            "d4M/5g7yBHJpIjWqSISXZ4",
            "d9SauC1PFP+pDw97Xry/9q",
            "daGsZSZltOxrGYQiFpfgKN",
            "dcw7Ahr4tEe74anfmvop70",
            "ddLurdqNBE2qsba2F9OLiY",
            "e8Mg/7OThO9Zzcq/Ol1Pru",
            "e9AtmCKv5PRrEpLV++kd97",
            "edseixoN1Jma0RTn4HTRVG",
            "eeIvxCHOtMl7XyuSJ26z5c",
            "ee8hpSWYBK6rpmU2PAl6KR",
            "f1t2Nai0pF0bSaGHSmQnP+",
            "f3tGaT96lHpawyXHKOBFoj",
            "f5hTxRpWZJUp/4V6q60AV4",
            "fauZOaLGFIsbPWvTEbF8r6"
        ],
        "06f81d253": [
            "6eXmBhpJBLm6PeO2KjWQLr",
            "feupchx91OKbFFaWxGQE6A"
        ],
        "0747c7b63": [
            "00gQ5BhoFCr4oxXsoeUJ6A",
            "008EI2Mp1FvoLKjkRIfHHr",
            "01YZJ9nVJLWoFTcEfa6zrq",
            "02delMVqdBD70a/HSD99FK",
            "04LUY/4CRLMrIN0pHfxVGr",
            "08AD33e2RJRqxA4NWpBu8y",
            "08EKPhiCZGWY6T9oL13E/0",
            "09eCr7il9IZpjKOhjRvUJW",
            "09/Cv2saJNaZn6IGMMvGIs",
            "0auYC/fRNA15BGP7rxr2FA",
            "0eMrquzzpB54yDNHN0zXZq",
            "0eNzWHzDBCx6CxEerXD8ZR",
            "0fCxyH3b9CboB6URGDzc50",
            "0fwIknddRMqY9/PnZK6XjD",
            "0f9Ekbb+hK16orI7fXoovD",
            "107CrqL2VFCKm7CO/Y36xj",
            "114D1uu8BJYY2qvmd1N/Bo",
            "129trwz71I74N37Ml6Jr1v",
            "13PuDSll5FU4RVGJtMDqxH",
            "17rkfo1ntI8o/wIfMnUt87",
            "19YjmtrxFMJpBqoFd0D2Tw",
            "1abouSJyNF7YYyURI7Fv+l",
            "1a5SkFekRB2oo0MdOkk+1x",
            "1bqw8h+UFDQJ7I6kiABNsZ",
            "21nsnpTuZNcLcrW5DIgBHt",
            "22Q+HFBSFIBLBQlwVx5itn",
            "23OEbfYfNJNb/dlTSkEKGE",
            "28t2nAIQBGebjWJiaKn9zZ",
            "29/9FSNtZHWb4aKu1gHQBw",
            "2dxNNWZnZDWpsjKhTFEo7Y",
            "31KTFa95pLpr+0rj17P6cW",
            "32F82HuHhDYat1ZLcEwxz5",
            "32t3QZmUtFubH0sj1KC7Ah",
            "333VrE/WpCVYQ8SVPtIOib",
            "339726ibVPWqEZBACjsqmW",
            "36i2wlEgVBsbqfyeBcibfa",
            "37WyIp0edE8KPLqUMIyK0b",
            "373RkIrbxEU5Aas6zR+nby",
            "3cQX2LVWlCrIPG09zjxQhJ",
            "3eqrDPWxpHOJd1ihfO+yCe",
            "43Kw0OpQJBHZhDakTGWjUF",
            "43imePjIdL1LYmm6RV217I",
            "44e50sZXRDk5B6c3tqtIt1",
            "441rczOkBOqLTyMyEA2tGr",
            "447rkYf51Bbrjoe4BzqNNq",
            "45Xw7VoYhGDbYl9p7XCTRu",
            "46OHt+JqRJYotB8NCR6T8u",
            "46hhtUYehFBKEtWe9WeosG",
            "47EKy+EPVMSJvKcnzbMmg6",
            "48PMmTET1DHoNbdOWFUJB2",
            "48joXCfWRJ44CImSKGBmxv",
            "493+GRnf9NbJRYMR9kqEtq",
            "4aYBYTI6VAD6+zaC2RmeF2",
            "4cGkTNBitCO5pSY0LwOAUE",
            "4cX5O6bhhCrI8GCI86R62Q",
            "51ouZJWDxGQZtWM86tNodD",
            "53kBLFLmlKxqopE1rdkc6d",
            "538r7fdLBLK6rowYbHaPJZ",
            "55LbxfHQFKlZRfv+BO097n",
            "56/LD1Tg1DNoFTtPcg6TXv",
            "57dbO7t3VEcK45cTgxM3HC",
            "572r2BJ45P27kG+pc6VHI/",
            "58APHyXIBOYYIIgrvIL97R",
            "5aGkWogiRGd624eVqNW8Ar",
            "5bwGMUoopDI6a80/ubMhul",
            "5b32D3zdNPcZnWx2FP6VCN",
            "5ciVJMVbVNU6Ng4V2uzmCo",
            "5ecKX8fX9PWJ/HagBd3m5J",
            "61oVvY8txDHYWUNHqk5+8N",
            "6130avOzRPsaPt7ClbEASJ",
            "63lZ1QffdFs5nytB+Xhf4v",
            "64FVVNX/lPQL+HHduCBlWz",
            "641+jaa/RAkLCqeISbKqg0",
            "66tHxlTqVOIKyPH/4hWWYg",
            "68Xu39TtZG+qL6Q1LerSZ4",
            "6a7qYjKHxNA612PNWF8ThV",
            "6cRZImlrtKRr4G4A7xaUnf",
            "6fDXvYrJRKlKtbgEEEEl0K",
            "70AsdwTvFJl4fK/1u8740G",
            "73Ew3Jp0FBIKxhJnZ7NKRc",
            "74uujqhkpJOpslmuZ2F8vf",
            "75f52OBd1Of7ihAhgPm7Pd",
            "76ZGK/kslHopuqN5rjM+Xg",
            "779MvOxqpFVq+sn+C6kRAx",
            "7aM/fsN1NDE4P3sFRo6rVf",
            "7bFnUpAZZLCYAJXIk3klFI",
            "7b1ytdcPpAsbtziXSphGy0",
            "7c6DNX8mxGbovmVHK0BhTR",
            "7c6Kal7XJPiJJO0cr0PDYN",
            "7fxC3sqY1IP4+6eOotO2Gu",
            "80KK9wZx1LU4dhfPeL1oLg",
            "81qlJqK6xIFr/WSg1FWa2L",
            "81sQeGE9pMG6gMS6kK4d3a",
            "82JBhl7U9F1LMdeRFJr0xJ",
            "82TCWmuKVOkLOr2N9Oqr7D",
            "87ilEzz3BJRb+vmAgATQ1T",
            "89de/fBKdIroD8O0YAtF9+",
            "8apzq/9ZBImqqSipkkAS6m",
            "8bE1fG3SxH8binfsTJjRef",
            "8bUl7fx75JEKk9gs+rcWce",
            "8cM5HoX6xIeLoUujT/G7xt",
            "8ckJNLcGdD2ppGSbj6ghuJ",
            "8dJXq8d81C2a/9EWg/xvAq",
            "8fE0rM5V5P3YfJJBAjZg+J",
            "8fPMdbRcJPj71a6IAdE4x5",
            "8fPadlN6BE0IW09V4wnJBX",
            "8fq5TCnCZAP48HMVZrf8r/",
            "90Iub34LBCRo7Ih4YuqO6f",
            "91QeVIB+BDv4KZV9UsEHOw",
            "91S0TYGgRKVJ3c7regyiHu",
            "91yIec4ZdFTpyFh7dcBK5N",
            "94Eg7aYMVOu5I5TPxjZUpB",
            "94wIpPHIxOr4An0ioyUqu0",
            "99r900btlLPb0BS5YPWky+",
            "9dVnUcT/5Co64GVDLQ25yZ",
            "9fJTkrPExBF76tdPXr4xIq",
            "a0BsFsLKNIAoBlB18yWWDc",
            "a6R0ENJYtPUpFpkNyuctTi",
            "a6lLd7x2VAjoA0CNaC7my7",
            "a75eqlC3JHAqAI4JeiiSVW",
            "a91XcLBApKerpf3g4VdZ8K",
            "aaE56q0mFADZAxCuRhH0ww",
            "aaYvlWOZZPfJdmuZh+urLz",
            "acJwBqn0lCg6a+A4KkBesp",
            "aefj9qWY1AWZG7xy+ZHjbP",
            "afjMuFrMBLzLGxoGOhVxuK",
            "aflsZlRUVIBaWLoRCRWI0v",
            "b0fjp7z+5HTJJYzL4DweZz",
            "b1BB572nJIXaBH5oIr33BL",
            "b1H9LuXfhF0r/mA5tePwSP",
            "b1bzp/IBFMZo2hrb3NmhPy",
            "b3hPBm33dOrqca95PfvhO4",
            "b57uGSHhxPNIwy+VECYl9b",
            "b7//bthBFCB7TgsW8Ow7o8",
            "bbSL4PqX1AybLM0FObcLAJ",
            "bd1NJLw0xPQpZn+4YQYcnp",
            "beQdzyqoJKT4M8TQmMuPxn",
            "c0WBM1GUNKkplgJPMukBWW",
            "c1IlA0S1NL0KiLZ1l0Z1dl",
            "c1WRWbmCxCerzEdlVmWH+1",
            "c4v+u44jZIjLklVb+AoDcq",
            "c5IO/YLDZOVZAKyu0GW57B",
            "c5Y7pQmgNPVqDvBiEgEEcn",
            "caR6rXR7hH1btHvRWMDdUY",
            "cdDVqS7jdOh4zTgy5qbPXN",
            "cdYfUUiUVORZZi519kggt9",
            "ceARKtQuFKjqxTEnV6JpEC",
            "cesFhx6ghOd7+IFTGRf/GE",
            "ce6IlD7wVC9ZR57m0HvlIh",
            "d3U6odn/hPDaNRfVObwyLi",
            "d4Q0fScmpCBZ7/OLwdsmDO",
            "d5K8wlgvhPKaiy1FoOr/4R",
            "d6DlERdvhGvpvsbXUvd2vA",
            "d6Zt6PK09NjbopgUXynx0t",
            "d6rO22xMNFkL9VdHmAZWXs",
            "d650CEa21GBagYLUPB4DQV",
            "dbJBenwmVJEaTYaR44t3NI",
            "ddYo1idmJEfbM8I/Alp8oT",
            "ddwp3OSF5A3JslKNWDQIw8",
            "deNuo4UnZNFZ89jWbzdLk5",
            "dfILE975xP7KbOBkg7XGEp",
            "e2Du+h7KBN9IqUs1o5LEeu",
            "e2SGF54CJJRq/KqQaQquxp",
            "e3s1GcbPtNd6ZjpdBOuHOv",
            "e5izpx4OlCAoWUqesdiAuQ",
            "e5pIMJwTdO0YCio61xr3jE",
            "e6G6+wPf1Bu7KyBRlHavJV",
            "e78at/E6hO+49wnW14ngZP",
            "e9A/lWdLlLG5nTDjgezT4g",
            "e9+MtwUu9JoZ6odSx/KdEZ",
            "ebQPRSL95NapVpn+Yz0kqe",
            "edfykgl+FFoYAoeD5T6SHI",
            "edpiCFvTtAZYC2+rObBOQL",
            "eemPucD2RD45y3ksaLt+qV",
            "eeyMUflm1EjbRyXqgMQJIw",
            "f2k2xuWnNJILd2mxLc95yO",
            "f35/FDbJdK8I2Fs5OAzJpK",
            "f5tZfAFoJK6IE3IgD9y54X",
            "f7u9FXmtJI4rYH9mMIERJe",
            "faj/75/y9EGLhBswId29JJ",
            "fbtyi36XpAArVBLxBg9Cfk",
            "fdX1VgE0BDyocBcR+8R7h7",
            "fdw91KoGRKmo90PYaZUsKa",
            "fd0qq/BWFCWaN7WFtUXrP4"
        ],
        "079499991": [
            "2aKWBXJHxKHLvrBUi2yYZQ",
            "6dkeWRTOBGXICfYQ7JUBnG"
        ],
        "07c8cf9a2": [
            "0ddgS2FmpMya8Laf7lDSnD",
            "0f04RpJNZCSJKPZUx4/O/Q",
            "17PxwbWS1Ps61J2aTFHnY9",
            "24DPYVtRRAZbGIxO94dlYz",
            "2erzjVAidCKJN12SYwczPd",
            "36MFSPMVFPELQJlRZyhmRc",
            "37PG/rFvNIaokCOYzM/AZ9",
            "3dIekwH7VHEp/88ewubbYW",
            "59Fqvc/ctH6ZpdmnITK8N5",
            "5aJct5pf9KrJLOcvbo6JyH",
            "5b8qDzDw9MmIfoAr+/fHel",
            "6fQMsWZapBEp4GWr1ykQhA",
            "7dMDA8iHdKp47YbphWeqFV",
            "82NH9RLcxH0p+zY7xLqkJy",
            "84wKut40NA+KC8Z/5qHZQJ",
            "95/amvJORNGYpbmAaqMA3m",
            "aaYWtUd9VKf7X07EYiL2Gl",
            "adr3XijbBIlZ3PeU4I6FKc",
            "aeBkqD1+9NXopwsj3ACUs9",
            "b0LzFMPNZMnbeoih5/NSt/",
            "c02XxJQd1KLaccwBPKOkd6",
            "c50CwyRRpJ2p2FNNDW5AAH",
            "c6RFF9oNVIK5yOjpv5SraX",
            "d5xowZ03dNRqlvH0TXFIs2",
            "e2UeGsGjtJjrLqHERrD/h/",
            "e4krZ2nzdGLIiazWxiK0EK",
            "e4uTTPCidHDquC1IGwjTpL",
            "e452s0o4JJh7EPbzIPLnEM",
            "ee25qaZNRCTI7z84Ts3I8f",
            "f2W0Sg8UpPoJLDeivhEWlz",
            "f7S1nL4lxGrKXpkWPRtXdS",
            "f7WfLB05tIlaQbh1tEmZpF"
        ],
        "07ce7530a": [
            "14TDKXr2NJ6LjvHPops74o",
            "3ae7efMv1CLq2ilvUY/tQi"
        ],
        "086061860": [
            "91U+XQfHRDlparf7w8MfsN",
            "c02XxJQd1KLaccwBPKOkd6",
            "e2UeGsGjtJjrLqHERrD/h/",
            "e452s0o4JJh7EPbzIPLnEM"
        ],
        "0871f1704": [
            "0f04RpJNZCSJKPZUx4/O/Q",
            "16jEGK+YhOS6FX0gDgd6l/",
            "16vBqe+v1DEqhRQwdSxPI7",
            "19Fvk/WSZDOb0AGw0cPOyH",
            "19Xr1IodpCpppXVo5IB79Z",
            "1fVTpK5ttANbRAZpJRJPZu",
            "29jW9wyHxOao5gkUwvdB9K",
            "2erzjVAidCKJN12SYwczPd",
            "36MFSPMVFPELQJlRZyhmRc",
            "37PG/rFvNIaokCOYzM/AZ9",
            "3dIekwH7VHEp/88ewubbYW",
            "5e651jp71LX7q6sA3DZ1Nu",
            "7dMDA8iHdKp47YbphWeqFV",
            "82NH9RLcxH0p+zY7xLqkJy",
            "836kjw7e9Ho4r48G78PXo5",
            "9eRt2iiitLy5uIcplYKwKW",
            "a4g4+2peBBLbfu/dvR2Lp9",
            "a55bIZkzhNeZeJ/TEB/jeo",
            "aaYWtUd9VKf7X07EYiL2Gl",
            "adr3XijbBIlZ3PeU4I6FKc",
            "aeBkqD1+9NXopwsj3ACUs9",
            "c1AeHw0vFOCJop8aUTow+N",
            "c50CwyRRpJ2p2FNNDW5AAH",
            "c6RFF9oNVIK5yOjpv5SraX",
            "cclcQryZxIDZh3LiD2ex5t",
            "ce2i29OgNK758NuwfxdrEu",
            "d6ur1ONfBEvZZQ6i/Uc/dk",
            "e4krZ2nzdGLIiazWxiK0EK",
            "e452s0o4JJh7EPbzIPLnEM",
            "ebOFHyPftHCaj2GSbOTEmF",
            "ee25qaZNRCTI7z84Ts3I8f",
            "f7WfLB05tIlaQbh1tEmZpF"
        ],
        "092afe77c": [
            "3dIekwH7VHEp/88ewubbYW",
            "eaIt/HIKNAtr5nMMLj7xsr"
        ],
        "0a471b9b6": [
            "98Sa5QvBFAZL7oKG376rdQ",
            "a6YyX0jCVHj4XXF4XTPOyV"
        ],
        "0a509f530": [
            "08XPgce3hL/YD6Sdd0GAT8",
            "0ddgS2FmpMya8Laf7lDSnD",
            "24DPYVtRRAZbGIxO94dlYz",
            "3126Eq/wtNeazDu6dhTx/T",
            "36MFSPMVFPELQJlRZyhmRc",
            "3dIekwH7VHEp/88ewubbYW",
            "3euf4XW71LM6h/UM2HgGSW",
            "41Pwmd+1JLLLI1/LsDwogk",
            "57uohAzctMG6NSGbgUgNOx",
            "5aJct5pf9KrJLOcvbo6JyH",
            "5fxfol3JBOP4ETCQc/Lx+9",
            "6fQMsWZapBEp4GWr1ykQhA",
            "82NH9RLcxH0p+zY7xLqkJy",
            "84wKut40NA+KC8Z/5qHZQJ",
            "844DoY4oVOeLu1fGsiZQGX",
            "9d+uXIr5VN7KXiY6H3VR/Y",
            "adr3XijbBIlZ3PeU4I6FKc",
            "aeBkqD1+9NXopwsj3ACUs9",
            "bbK102zWpLmZ/GhJXc/nTE",
            "c6RFF9oNVIK5yOjpv5SraX",
            "e4krZ2nzdGLIiazWxiK0EK",
            "e4mox6w4hF5IJdFlki+I5j",
            "e4uTTPCidHDquC1IGwjTpL",
            "f7S1nL4lxGrKXpkWPRtXdS",
            "f7WfLB05tIlaQbh1tEmZpF"
        ],
        "0a5cba09d": [
            "2afAA24LNP4YmYiaVLiivs",
            "46bU+b5fROqIXVPG6aZWWK"
        ],
        "0ad1785b2": [
            "0fAH04bu5H87uz9W4l3Cxm",
            "17yES88MpFJZwov14Q5Y04",
            "22jRKKuf9E8ZKozNHJF7lR",
            "29987TIdRDTpe7Hl5taW01",
            "2dce1/9AVLW4g/l8StcWI2",
            "2eoUAvDK9N2r6VTBn40My9",
            "33HROs5VFNaJgrrohxJUqh",
            "36HTLVtNZIS5OypMwUwzLr",
            "48Y5ZgChJJer7CeK8DYAm5",
            "4bMPkcOqlAnY0lKLSREup+",
            "51ZGjqnhFFOYZYyOpC3HtB",
            "582+zq5lJJgrVMNClPMZr8",
            "64WhgKHkNFSadH8d/Zb0RW",
            "6aUzpTB5lL0pQbz/MiPVlm",
            "6crjttS0JDF7kdBgLldjF4",
            "71SYsbj1RAVoYeWbjssKgB",
            "77oFgADcNCN6+y0ciiQHN7",
            "81sx/b7sNIP4H5Vl9dAOTw",
            "826gzLhLNP6bEaEyoUoi+9",
            "871OekBZxARYGv3l38mnoA",
            "943De4wp9H7ZxqPSwkxEoJ",
            "a2DJRploFGe75jDvgSbIno",
            "a8V5xQn7RI5azzgXy4drso",
            "a9vawIyEVM2LEcQQ3F+aLB",
            "b7my8OLGdIvZ/6nm+8cLId",
            "b9uvmo2YJJ7YeqduPEZHig",
            "daL0i0/1FEnq1IKr05t5Gx",
            "ddxfFdm8NLTbygAMh+bhel",
            "edouHnez5LNrPSJnj0DLxp",
            "f7kP/6sKlLarYGfRotItXV",
            "f79Rm0uJ1GKLGcxpGYjzWB",
            "ff2SvuWkJA8Y0wP/CM+IQR"
        ],
        "0bc42f27f": [
            "0ddgS2FmpMya8Laf7lDSnD",
            "0f04RpJNZCSJKPZUx4/O/Q",
            "13VY83XL9Gr7Wzt942LCWY",
            "17PxwbWS1Ps61J2aTFHnY9",
            "19Fvk/WSZDOb0AGw0cPOyH",
            "24DPYVtRRAZbGIxO94dlYz",
            "36MFSPMVFPELQJlRZyhmRc",
            "37PG/rFvNIaokCOYzM/AZ9",
            "3dIekwH7VHEp/88ewubbYW",
            "59Fqvc/ctH6ZpdmnITK8N5",
            "5aJct5pf9KrJLOcvbo6JyH",
            "5b8qDzDw9MmIfoAr+/fHel",
            "6fQMsWZapBEp4GWr1ykQhA",
            "71SXaL5sxLjIQj7FWxCYst",
            "7dMDA8iHdKp47YbphWeqFV",
            "82NH9RLcxH0p+zY7xLqkJy",
            "84wKut40NA+KC8Z/5qHZQJ",
            "95/amvJORNGYpbmAaqMA3m",
            "aaYWtUd9VKf7X07EYiL2Gl",
            "adr3XijbBIlZ3PeU4I6FKc",
            "aeBkqD1+9NXopwsj3ACUs9",
            "b0LzFMPNZMnbeoih5/NSt/",
            "c02XxJQd1KLaccwBPKOkd6",
            "c50CwyRRpJ2p2FNNDW5AAH",
            "c6RFF9oNVIK5yOjpv5SraX",
            "d5xowZ03dNRqlvH0TXFIs2",
            "e2UeGsGjtJjrLqHERrD/h/",
            "e4krZ2nzdGLIiazWxiK0EK",
            "e4uTTPCidHDquC1IGwjTpL",
            "e452s0o4JJh7EPbzIPLnEM",
            "ee25qaZNRCTI7z84Ts3I8f",
            "f7S1nL4lxGrKXpkWPRtXdS"
        ],
        "0bd34f42c": [
            "0f04RpJNZCSJKPZUx4/O/Q",
            "16vBqe+v1DEqhRQwdSxPI7",
            "19Xr1IodpCpppXVo5IB79Z",
            "1fVTpK5ttANbRAZpJRJPZu",
            "24DPYVtRRAZbGIxO94dlYz",
            "2erzjVAidCKJN12SYwczPd",
            "36MFSPMVFPELQJlRZyhmRc",
            "37PG/rFvNIaokCOYzM/AZ9",
            "3dIekwH7VHEp/88ewubbYW",
            "5e651jp71LX7q6sA3DZ1Nu",
            "6c1/VfNCJGj74VFE88Y6V7",
            "7dMDA8iHdKp47YbphWeqFV",
            "82NH9RLcxH0p+zY7xLqkJy",
            "836kjw7e9Ho4r48G78PXo5",
            "9eRt2iiitLy5uIcplYKwKW",
            "a4g4+2peBBLbfu/dvR2Lp9",
            "a55bIZkzhNeZeJ/TEB/jeo",
            "aaYWtUd9VKf7X07EYiL2Gl",
            "adr3XijbBIlZ3PeU4I6FKc",
            "aeBkqD1+9NXopwsj3ACUs9",
            "c1AeHw0vFOCJop8aUTow+N",
            "c50CwyRRpJ2p2FNNDW5AAH",
            "c6RFF9oNVIK5yOjpv5SraX",
            "cclcQryZxIDZh3LiD2ex5t",
            "ce2i29OgNK758NuwfxdrEu",
            "d6ur1ONfBEvZZQ6i/Uc/dk",
            "e4krZ2nzdGLIiazWxiK0EK",
            "e452s0o4JJh7EPbzIPLnEM",
            "ebOFHyPftHCaj2GSbOTEmF",
            "ee25qaZNRCTI7z84Ts3I8f",
            "f7WfLB05tIlaQbh1tEmZpF"
        ],
        "0c038841a": [
            "06bVn1APpKv7FMEK5Id3kQ",
            "feupchx91OKbFFaWxGQE6A"
        ],
        "0d669730c": [
            "c0BAyVxX9JzZy8EjFrc9DU",
            "cffgu4qBxEqa150o1DmRAy"
        ],
        "0da3de303": [
            "0f04RpJNZCSJKPZUx4/O/Q",
            "16vBqe+v1DEqhRQwdSxPI7",
            "1fVTpK5ttANbRAZpJRJPZu",
            "24DPYVtRRAZbGIxO94dlYz",
            "2erzjVAidCKJN12SYwczPd",
            "36MFSPMVFPELQJlRZyhmRc",
            "37PG/rFvNIaokCOYzM/AZ9",
            "3aGn6oq0pOoYa5DXtWOY7/",
            "3dIekwH7VHEp/88ewubbYW",
            "5b8qDzDw9MmIfoAr+/fHel",
            "5e651jp71LX7q6sA3DZ1Nu",
            "7dMDA8iHdKp47YbphWeqFV",
            "82NH9RLcxH0p+zY7xLqkJy",
            "836kjw7e9Ho4r48G78PXo5",
            "9eRt2iiitLy5uIcplYKwKW",
            "a4g4+2peBBLbfu/dvR2Lp9",
            "a55bIZkzhNeZeJ/TEB/jeo",
            "aaYWtUd9VKf7X07EYiL2Gl",
            "adr3XijbBIlZ3PeU4I6FKc",
            "aeBkqD1+9NXopwsj3ACUs9",
            "c1AeHw0vFOCJop8aUTow+N",
            "c50CwyRRpJ2p2FNNDW5AAH",
            "c6RFF9oNVIK5yOjpv5SraX",
            "cclcQryZxIDZh3LiD2ex5t",
            "ce2i29OgNK758NuwfxdrEu",
            "d6ur1ONfBEvZZQ6i/Uc/dk",
            "e4krZ2nzdGLIiazWxiK0EK",
            "e452s0o4JJh7EPbzIPLnEM",
            "ebOFHyPftHCaj2GSbOTEmF",
            "ee25qaZNRCTI7z84Ts3I8f"
        ],
        "0dab168f8": [
            "0ddgS2FmpMya8Laf7lDSnD",
            "0f04RpJNZCSJKPZUx4/O/Q",
            "19Fvk/WSZDOb0AGw0cPOyH",
            "1fVXgvl0hGObqbZcFW+CAj",
            "24DPYVtRRAZbGIxO94dlYz",
            "2erzjVAidCKJN12SYwczPd",
            "36MFSPMVFPELQJlRZyhmRc",
            "37PG/rFvNIaokCOYzM/AZ9",
            "3dIekwH7VHEp/88ewubbYW",
            "5aJct5pf9KrJLOcvbo6JyH",
            "6fQMsWZapBEp4GWr1ykQhA",
            "7dMDA8iHdKp47YbphWeqFV",
            "82NH9RLcxH0p+zY7xLqkJy",
            "84wKut40NA+KC8Z/5qHZQJ",
            "a6IaA4XKZFNKhNhiifT8AF",
            "aaYWtUd9VKf7X07EYiL2Gl",
            "adr3XijbBIlZ3PeU4I6FKc",
            "aeBkqD1+9NXopwsj3ACUs9",
            "c02XxJQd1KLaccwBPKOkd6",
            "c50CwyRRpJ2p2FNNDW5AAH",
            "c6RFF9oNVIK5yOjpv5SraX",
            "c8+qc2mdJBVLvYQIlHqBih",
            "cclcQryZxIDZh3LiD2ex5t",
            "ccyp4Ts+FMs6kAkyECgIcf",
            "d9R2w8GvhCvpX5ok6iEzzm",
            "e2UeGsGjtJjrLqHERrD/h/",
            "e4krZ2nzdGLIiazWxiK0EK",
            "e4uTTPCidHDquC1IGwjTpL",
            "e452s0o4JJh7EPbzIPLnEM",
            "e6K5fUo/hESqkCdmgs255J",
            "ee25qaZNRCTI7z84Ts3I8f",
            "f2+3OFeUhNV4Jq2yGqmlIQ",
            "f7S1nL4lxGrKXpkWPRtXdS",
            "f7WfLB05tIlaQbh1tEmZpF"
        ],
        "0e16adf91": [
            "12EGVp+R9LA5ySxBniJh5n",
            "195JJ7XfRJ+6GHw787VZ+O",
            "1ejcmR7/tHoZbeN7t/tk2c",
            "2bAIEVrqNGYbUtUmkOaza2",
            "33+aCPnn9J2KSViOcZI0CG",
            "36BThHM4FMUJKhBtryLKnv",
            "3c7aib/vtB07wQo1sWkWKE",
            "44qRE7y+1Fr4Q6xLGpKFRt",
            "52nXVHcKxOfo7KxXi3Nvgq",
            "6dSmMJgDFGUo3oskN1SNvf",
            "783MekGthM2LkbLLV97G1t",
            "84mGpIMMFDxb5BSBKHj+P1",
            "85BwqEyyRKGovG3aRSfLBr",
            "8chxmVY4pHtLAsbdTrHIBZ",
            "96fucGSHZE/rzBn7r+ZvR7",
            "98eodJRXdJ4ro0VfzbEh69",
            "a7Iyasyp9LP7GaKII6t02E",
            "b1+tN2oyJLeqKyoL5bMikA",
            "b4m+v+9ctGBYHaprxJk5vh",
            "beMgE1hdRBw6W/D3q+6ao0",
            "c6gZ5EDHdFr7uD0T2fS8vu",
            "c6jQ2IXFpENKUGLycN5BbQ",
            "ea+bNPASlBTqNTs1UQJYnq"
        ],
        "0e4bc3b03": [
            "0ek66qC1NOQLjgYmi04HvX",
            "7a/QZLET9IDreTiBfRn2PD"
        ],
        "0f62e2a77": [
            "01MSVhOTFJaITqxT5LFQfZ",
            "04q7i5v69EN4+EzsywUA4E",
            "17PxwbWS1Ps61J2aTFHnY9",
            "3cllxhTP9MNJ3S20pZI7Lu",
            "54JXCQbblG7poZXRvij0/E",
            "58XRAVpX1CUJBuWVrpxkLD",
            "685XxBF2FMlpFsJd67N1yT",
            "790JBonXVBXJFLy9dCHPaX",
            "94oX98WyZJfKT5usMmQfMN",
            "b5IwdVURRN4JdFp7mEMWms",
            "b5r4QzLDBE/bWRLB4aDXxe",
            "bd0dceEQlGqZDhI5PVEvEA",
            "daHlQoZpNKab7WrGW8oPZu",
            "de2YFtn2dAJLlo4aoa8HSX"
        ]
    },
    md5AssetsMap: {},
    orientation: "landscape",
    debug: true,
    subpackages: {}
};
